def/proto1/config/routes.rb
Proto1::Application.routes.draw do

  root :to => "login#login"

  resource :feedback, :only=>[:new, :create]
  resource :contact, :only=>[:new, :create], :controller=>'feedback',
           :type=>'contact_us', :as=>:contact_us
  resources :usage_stats, :only => :create

  resources :phr_home, :only => :index
  get '/phr_home/export_one_profile/:id_shown(/:file_format/:file_name)' =>
                                                   'phr_home#export_one_profile'
  get '/phr_home/get_name_age_gender_updated_labels'
  get '/phr_home/get_removed_listings'
  get '/phr_home/get_one_active_profile_listing'
  get '/phr_home/get_initial_listings'
  get '/phr_home/get_others_listings'
  get '/phr_home/get_access_list'
  put '/phr_home/remove_access'

  post '/share_invitation' => 'share_invitation#create'
  post '/share_invitation/accept_invitation(/:sent_to/:invite_data)' =>
                                      'share_invitation#accept_invitation'
  match '/share_invitation/accept_invitation' =>'share_invitation#accept_invitation',
      :as => 'accept_invitation', :via => [ :get]
  get '/share_invitation/get_pending_share_invitations'
  post '/share_invitation/update_invitations'

  get '/phr_records/archived'=>'phr_records#archived_index', :as=>"archived_phr_records"
  get '/phr_records/message_managers'=>'phr_records#message_managers',
    :as => "message_managers"
  put '/phr_records/:id/archive'=>'phr_records#archive', :as=>"archive_phr_record"
  put '/phr_records/:id/unarchive'=>'phr_records#unarchive', :as=>"unarchive_phr_record"

  resources :phr_records do
    member do
      post 'archive'
      post 'unarchive'
      get 'edit_phr'
      put 'update_phr'
      match 'export', :via => [:get, :post]
    end
    resources :phr_drugs do
      get 'search', :on => :member
    end
    resources :phr_conditions do
      get 'search', :on => :member
      match 'studies', :on=>:collection, :via=>[:get, :post]
    end
    resources :phr_surgical_histories do
      get 'search', :on => :member
    end
    resources :phr_doctor_questions
    resources :phr_medical_contacts
    resources :phr_allergies
    resources :phr_immunizations
    resources :phr_notes

    resources :reminder_options do
      get 'search', :on => :member
    end
    resources :date_reminders do
      get 'hidden', :on => :collection
      member do
        post 'unhide'
        post 'hide'
      end
    end
    resources :phr_panels do
      get 'search', :on => :member
      match 'flowsheet', :via => [:get, :post], :on => :collection
      match 'get_paginated_flowsheet_data_hash', :via => [:get], :on => :collection
      resources :items, :controller=>:phr_panel_items
    end
  end

  get '/phr_records/:id/reminders'=>'phr_records#reminders', :as => "phr_record_reminders"

  get '/captcha/show'=>'captcha#show', :as => "captcha"
  post '/captcha/answer'=>'captcha#answer', :as => "captcha_answer"
  resources :phr_records, :as => "profiles", :controller=> "phr_records"

  match '/accounts/login(.:format)' => 'login#login', :form_name =>'login',
    :as => 'login',  :constraints => { :format => /(default|basic|mobile|)/ },
    :via => [:get, :post]

  match '/accounts/delete_account'=> 'login#delete_account',
    :as=>'delete_account', :via=>[:get, :delete]

  constraints :format=>'' do  # disables URLs like /accounts/new.tmp
    match '/accounts/new' => 'login#add_user', :as => "account_sign_up",
      :via => [:get, :post]
    match '/accounts/email_verification' => 'login#email_verification', :as=>"email_verification",
          :via=> [:get, :post]

    get '/accounts/get_reset_link' => "login#get_reset_link"
    match '/accounts/two_factor' => 'login#handle_two_factor', :form_name=>'login',
      :as => "confirmid", :via =>[:get, :post]
    match '/accounts/reset_account_security' =>'login#reset_account_security',
      :as => 'reset_account_security', :via => [ :get, :post]
    match '/accounts/verify_password' => "login#verify_password",
      :via => [:get, :post, :put]
    match '/accounts/change' => 'login#change_account_settings',
      :as => "account_settings" , :via => :all# includes all http verbs
    match '/accounts/forgot_password' =>'login#forgot_password',
      :as => "reset_password_step_one", :via => [:get, :post]
    match '/accounts/forgot_id' =>'login#forgot_id',
      :as=>"recover_account_id_step_one", :via => [:get, :post]
    post '/accounts/forgot_id_step2' => 'login#forgot_id_step2',
      :as =>"recover_account_id_step_two"
    match '/accounts/change_password' => 'login#change_password',
      :as=>"reset_password_step_two", :via => [:get, :post]
    match '/accounts/update_password' => 'login#update_password',
      :as => 'reset_password_step_three', :via =>[:get, :post]
    match '/accounts/logout' =>'login#logout', :via => :all

    get '/application/extend_session', :as=>'extend_session'
    get '/login/timeout_logoff'

    match '/accounts/demo_login' => 'login#demo_login', :as=>'demo_login',
      :constraints => { :format => /(default|basic|mobile|)/ }, :via => [:get, :post]
  end

  %w(run_tests report_results).each do |action_name|
    get "/acceptance/#{action_name}", controller: 'acceptance', action: action_name, as: "acceptance_#{action_name}"
  end

  match '/forms/:form_name/rules' => "rule#show_rules", :as => "rules",
    :via => [:get, :post]
  match '/forms/:form_name/rules/new' => "rule#new_rule",
    :rendering_form => "edit_general_rule",
    :type => Rule::GENERAL_RULE.to_s,
    :via  => [:get, :post]

  match '/forms/:form_name/rules/:id;edit' => "rule#edit_rule",
    :rendering_form => 'edit_general_rule',
    :via  => [:get, :put]

  match '/forms/:form_name/case_rules/new' => "rule#new_rule",
    :rendering_form => "edit_case_rule",
    :type => Rule::CASE_RULE.to_s,
    :via  => [:get, :post]

  match '/forms/:form_name/case_rules/:id;edit'=> "rule#edit_rule",
    :rendering_form => 'edit_case_rule',
    :via  => [:get, :put]

  match '/rules' =>'rule#index', :via => [:get, :post]

  match '/rule/get_rule_name_list', :via => [:get, :post]

  post '/form/handle_combo_field_change'

  match '/fetch_rules/new' => "rule#new_data_rule",
    :rendering_form =>'edit_phr_fetch_rule',
    :type => Rule::FETCH_RULE.to_s,
    :via  => [:get, :post]

  match '/fetch_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form =>'edit_phr_fetch_rule',
    :via  => [:get, :put]

  match 'form/handle_data_req_for_db_field', :via => [:get, :post]

  match '/reminder_rules/new' => "rule#new_data_rule",
    :rendering_form => "new_reminder_rule",
    :type => Rule::REMINDER_RULE.to_s,
    :via  => [:get, :post]

  match '/reminder_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form => "new_reminder_rule",
    :via  => [:get, :put]

  get '/reminder_rules/show' => "rule#show_reminder_rules",
    :readable_format => 'false'

  get '/reminder_rules/show_in_readable_format' => "rule#show_reminder_rules",
    :readable_format => 'true'

  match '/value_rules/new' => "rule#new_data_rule",
    :rendering_form => "new_value_rule",
    :type => Rule::VALUE_RULE.to_s,
    :via  => [:get, :post]

  match '/value_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form => "new_value_rule",
    :via  => [:get, :put]

  get '/form/get_reviewed_reminders'

  post '/form/update_reviewed_reminders'

  get '/form/get_reminder_count'

  get '/form/get_profiles_updatetimes'

  match '/form/get_prefetched_obx_observations',
    :via  => [:get, :post]

  match '/class_types/' => 'classification#show_class_types',
    :form_name => "classifications", :via => [:get, :post]

  match '/classifications/:parent_id;parent_id' => 'classification#show',
    :form_name => "classifications", :via => [ :get, :post]

  match '/class_types/new' => "classification#new_class_type",
    :form_name => "classification",
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:parent_id;parent_id/new' => "classification#new",
    :form_name => "classification",
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :post]

  match '/class_types/new_item' => 'classification#new_class_type',
    :form_name => "classification",
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:parent_id;parent_id/new_item' => 'classification#new',
    :form_name => 'classification',
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:id;edit' => 'classification#edit',
    :form_name => 'classification',
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :put]

  match '/data_classes/:id;edit' => 'classification#edit',
    :form_name => 'classification',
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :put]

  match '/form/get_search_res_list_by_list_desc', :via => [ :get, :post]

  get '/data'=>'data#index'

  get '/data/export/:id'=>'data#export', :format=>'csv'
  get '/data/export_form_text/:id'=>'data#export_form_text', :format=>'csv'
  post '/data/update'

  match '/help_text'=>'help_text#index', :via => [ :get, :post]
  get '/help_text/list' # list of all help files
  match '/help_text/new', :via => [ :get, :post]
  match '/help_text/edit/:id'=>'help_text#edit', :via => [ :get, :post]

  get '/forms/new' =>'formbuilder#new_form', :form_name=>'FormBuilder'
  post '/forms' => 'formbuilder#save_form'
  get '/forms/:form_name;edit'=>'formbuilder#edit_form'

  get '/admin_home' => 'form#form_index', :form_name=>'admin'

  class RestrictPhrIndexToTests
    def matches?(request)
      Rails.env == 'test'
    end
  end
  get '/profiles' => 'form#form_index', :form_name=>'phr', :as => "profiles_std",
                                     :constraints => RestrictPhrIndexToTests.new

  get '/profiles/:id;edit' => 'form#edit_profile_with_form',
    :form_name=>'phr', :as=>'edit_phr'

def/proto1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proto1</title>
  <%#= stylesheet_link_tag    "application", :media => "all" %>
  <%#= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

def/proto1/app/views/layouts/basic.erb
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=ISO-8859-1" />
    <title><%= @page_title %></title>
    <%#= stylesheet_link_tag '/stylesheets/basic_html' %>
    <%= stylesheet_link_tag 'basic_html' %>
  </head>
  <body>
    <% if @user %>
      <div id="topnavbar"><% if @phr_record and @phr_record.phr and !@phr_record.phr.pseudonym.blank? %>
        <span id="record_label">PHR for: <%=  @phr_record.phr.pseudonym %></span>
        &nbsp; <% end %><% if !@hide_account_settings %><%=
         link_to 'Accounts Settings', account_settings_path %> &nbsp; <% end %>
       <%= help_button '/help/basic_general.shtml' %> &nbsp;
       <%= link_to 'Feedback', new_feedback_path %> &nbsp;
       <%= link_to 'Logout', '/accounts/logout' %></div>
    <hr />
    <% end %>
    <h1><%= @page_title %></h1>
    <%# Notification div %>
    <% unless flash[:notice].blank? %>
      <div id="notification"><%= flash[:notice] %></div>
    <% else %>
      <div id="notification" style="display: none"></div>
    <% end %>
      
    <%# Page errors div %>
    <% if flash[:error]
         @page_errors = [] if !@page_errors
         if flash[:error].is_a?(String)
           @page_errors << flash[:error]
         else
           @page_errors += flash[:error]
         end
       end
    %>
    <% if @page_errors && @page_errors.size > 0 %>
      <div id="page_errors">
        <% if @page_errors.size == 1 %>
        <p>The following problem was found:
          <%= @page_errors[0] %></p>
        <% else %>
          The following problems were found:
          <ul>
            <% @page_errors.each do |e|
               if e == '</ul>' %>
                <%= e %>
            <% elsif e.index('<ul>')%>
              <li><%=e%>
            <% else %>
              <li><%=e%></li>
            <%end; end%>
          </ul>
        <% end %>
      </div>
    <% else %>
      <div id="page_errors" style="display: none"></div>
    <% end %>    
    
    <%= yield %>
    <% if @user %>
      <hr />
      <div id="timeout_warning">Your session will time out in
       <%= @session_timeout %> minutes from when this page was loaded.  If you
       need more time, you may <%= link_to 'extend your session',
        extend_session_path, :target=>'_blank' %>.</div>
    <% end %>
  </body>
</html>

def/proto1/app/views/layouts/def_mailer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html> 
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
<%= yield %>
  </body>
</html> 

def/proto1/app/views/layouts/form.rhtml.erb
<!DOCTYPE html>
<% cache(Rails.env + '/layout_part1'+@form_cache_name) do %>
<html lang="en">
<head>
  <%#= the X-UA-Compatible has to be on the top of headers other than meta, title headers %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <script type="text/javascript">
    var startLoad_ = new Date().getTime();
  </script>
  <meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
<% end # cache- layout part 1 %>
<% if @profile_banner.nil?    %>
  <title><%= @form_title || @form.form_title %></title>
<% else %>
  <title><%= @profile_banner %></title>
<% end %>

<% cache(Rails.env + '/layout_part2'+@form_cache_name) do %>
  <%= stylesheet_link_tag_for_vendor "/vendor_assets/jquery-ui_css/jquery-ui", :media => "screen" %>
  <%= stylesheet_link_tag_for_vendor "/vendor_assets/jeegoocontext_css/style", :media => "screen" %>
  <%= stylesheet_link_tag_for_vendor "/vendor_assets/autocomp/source/auto_completion.css", :media => "screen" %>
  <%= stylesheet_link_tag "manifest_base_package", :media => 'screen' %>
  <%= stylesheet_link_tag "manifest_form_layout_common.css", :media => "screen" %>
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin" media="all"/>
  <% @form_style.each do |style| %>
   <!-- <%= style %> -->
    <%= stylesheet_link_tag style.strip, :media => "screen" %>
  <% end %>


  <% @print_style.each do |style| %>
    <%= stylesheet_link_tag style.strip, :media => "print" %>
  <% end %>
  <%#= javascript_include_tag "manifest_page_top" %>
  </head>


 <body onmouseup="Def.hideSaveNotice()"
       onkeydown="Def.hideSaveNotice()"
	     onload="BrowserDetect.checkBrowserSupport()">

  <div id="loading_msg" style="display:none">
    Loading ... Please Wait<br/>
    <%= image_tag("loader.gif", :alt=>"") %>
  </div>
  <!-- use javascript to turn display on for the loading_msg, so that
       it doesn't obscure the "Javascript is Required" message for
       instances where javascript is not enabled. -->
  <script type="text/javascript">
    var loadingMsg = document.getElementById('loading_msg');
    // repostion the msg box to the center of the window
    //loadingMsg.style.left = (window.innerWidth - (400+44))/2  + 'px';
    //loadingMsg.style.top = (window.innerHeight - (60+44))/2 + 'px';
    loadingMsg.style.display = 'block' ;
  </script>
<div id="content" style="display: none">
  <a id="skip_link" href="#formContent">Skip to Main Content</a>
<% end # cache- layout part 2 %>

  <%= yield %>
<script type="text/javascript" charset="utf-8">
    window._token = '<%= form_authenticity_token -%>';
</script>
<% cache(Rails.env + '/layout_part3'+@form_cache_name) do %>
  </div> <!-- end content -->
  <div id="reader_log" class="screen_reader_only" aria-live='assertive'
   aria-relevant='additions' role='log'></div>
  <div id="reader_alert" class="screen_reader_only" aria-live='assertive'
   role='alert'></div>
  <div id="validation_errors" class="screen_reader_only errReqDiv">
    <div class='closingLink'>
      <a href='#label' onclick='Def.Validation.RequiredField.ErrDisplay.closeFloating();'>Close X</a>
    </div>
    <div id="validation_alert" role='alert' aria-live='assertive'
     aria-relevant='additions' ></div>
  </div>
 <%# In most cases, there should be something output to the generated
     javascript file. %>
 <!-- need to reload generated js file when its content changed -->
 <%# generate_form_js(@form_name, @form_cache_name) unless @using_cache_files %>
  <!-- include both generated and form-specific javascript files if they exist -->
 <%= javascript_include_tag_for_form @form_name, @form_cache_name %>
  <script type="text/javascript">//<![CDATA[
    // Put this here, after all other load event handlers have been set up,
    // so it runs last.
    Event.observe(window, 'load', function() {
      $('content').style.display = 'block';
      $('loading_msg').style.display = 'none' ;
      var time = 'Loaded in ' +(new Date().getTime() - startLoad_)/1000 +
       ' seconds';
      var msgDiv = $('fe_load_time_td');
      if (msgDiv) {
        msgDiv.innerHTML = time;
        setTimeout("$('fe_load_time_td').innerHTML=' '", 15000);
      }
      Def.pageLoadComplete_ = true;
      //setTimeout(function() {Def.pageLoadComplete_ = true}, 500);
    });
	</script>

  <noscript><br /><br /><center><font size=+3>Javascript is Required</font>
  <br /><br /><p>Javascript must be enabled for your browser in order to
  view and use the PHR pages effectively.  <br /><br />It does not seem to be
  enabled for your browser at this time.  <br /><br />To enable Javascript check
  the <b>help</b> information provided by your browser.&nbsp;  This is available
  from<ul><li>the <b>Help</b> pulldown menu at the top of the page in the
  Firefox browser,</li><li>from the help question mark button
  <%= image_tag("blank.gif", :class=>"sprite_icons-help", :align=>"bottom",
        :alt=>"blue circle with question mark inside") %>
  at the top right of the tab line
  on Microsoft's Internet Explorer,</li><li>and in similar locations on other
  browsers.</li></ul></p></center>
  </noscript>
 <% end # cache- layout part 3 %>

  <!-- We only need the browser_close stuff if the user is logged in -->
  <!-- AND we're not testing -->
  <% if Rails.env != 'test' && session[:user_id]%>
    <%= javascript_include_tag "manifest_logged_in"%>
  <% end %>
</body>
</html>

def/proto1/app/views/layouts/mobile.erb
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.css"-->
  <!-- script src="https://code.jquery.com/jquery-1.10.2.min.js"></script -->
  <!--script src="https://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js"></script-->
  <%= stylesheet_link_tag "manifest_mobile.css" %>
  <%= javascript_include_tag "manifest_mobile.js" %>
  <title><%= @page_title %></title>
</head>
<body>


<div data-role="page"><%# start of data-role page%>
  <% if @user %>
      <div data-role="panel" id="userAccountPanel" data-position="left">
        <%= render({:partial => 'mobile/phr_records/user_account_panel.html', :handlers => [:erb],
                    :locals => {:user => @user}}) %>
      </div>
  <% else %>
      <div data-role="panel" id="pageFooterPanel" data-position="left">
        <%= link_to_mp "User Agreement", "/help/user_agreement.shtml?go_back=false",  :target=>"_blank" %>
        <%= link_to_mp "Privacy Policy", "/help/privacy_policy.shtml?go_back=false", :target=>"_blank" %>
        <%= link_to_mp "Help", "/help/general.shtml?go_back=false", :target=>"_blank" %>
        <%= link_to_mp "PHR Support", "/contact/new" %>
      </div>
  <% end %>

  <div data-role="header" data-add-back-btn="false">
    <% editing_patient_record = @data_rec || @phr_condition || @phr_drug || @phr_surgery || @reminder_option %>
    <% if @table == "reminder_options" %><%# reminder_options index page is different from pages list phr_conditions etc. needs to have a close button %>
      <%= link_to "Close", '',"onclick"=>"window.close()", "class" => "ui-btn ui-icon-delete ui-btn-icon-left" %>
    <% else %>
      <% if !editing_patient_record %><%# not when editing phr-condtiion etc%>
        <% if @phr_record %>
            <% if @reminders || @records || @saved_panel_info || (@page_title ==PhrPanelsController::PANELS_SECTION_TITLE ) %>
                <%#= link_to "PHR", phr_record_path(@phr_record),"class" => "ui-btn ui-icon-carat-l ui-btn-icon-left" %>
                <%= link_to @phr_record.phr.pseudonym, phr_record_path(@phr_record), "class" => "ui-btn ui-icon-carat-l ui-btn-icon-left" %>
            <% elsif @page_title == "Panel Flowsheet"  %>
            <%# visually separated the basic mode flowsheet page into two pages:%>
            <%# one for the settings another for displaying flowsheet%>
                <% if @flowsheet %>
                   <%= link_to 'Panel Flowsheet Settings', flowsheet_phr_record_phr_panels_path(@phr_record),  "data-ajax"=>false  ,"class" => "ui-btn ui-icon-carat-l ui-btn-icon-left" %>
                <% else  %>
                   <% @page_title ="Panel Flowsheet Settings" %>
                   <%= link_to PhrPanelsController::PANELS_SECTION_TITLE, phr_record_phr_panels_path(@phr_record), "class" => "ui-btn ui-icon-carat-l ui-btn-icon-left"%>
                <% end %>
            <% else %>
                <%#= link_to 'Profiles', phr_records_path ,"class" => "ui-btn ui-icon-carat-l ui-btn-icon-left" %>
                <%= link_to "PHR Home", phr_records_path, "class" => "ui-btn ui-icon-carat-l ui-btn-icon-left ui-corner-all ui-shadow " %>
            <% end %>
        <% end %>
      <% end %>
    <% end %>
    <h1><%#= @page_title %></h1>
    <% if !editing_patient_record || (@page_title =="Test Results & Trackers") %>
        <% if @user %>
            <% if @phr_records %>
                <a href="#userAccountPanel" class="ui-btn ui-corner-all ui-icon-bars ui-btn-icon-notext">User Account
                  Panel</a>
            <% end %>
        <% else %>
            <a href="#pageFooterPanel" class="ui-btn ui-corner-all ui-icon-bars ui-btn-icon-notext">Page Footer
              Panel</a>
            <%# render back button%>
        <% end %>
        <% url= send('new_phr_record_'+@table.singularize+'_path', @phr_record) if @table && @phr_record %>
        <% url = new_phr_record_phr_panel_path(@phr_record) if @saved_panel_info %>
        <% url= new_phr_record_path if @user && @phr_records %>
        <%= link_to 'Add', url, "data-icon" => "plus", "class" => "ui-btn-right" if url && @table !="reminder_options" %>
    <% end %>
  </div><%# end of page header%>

  <div data-role="main" class="ui-content"><%# start of data-role main%>
    <% if @page_title %> <h2 class="groupHeader"><span><%= @page_title %></span></h2>
    <% end %>      <!--p>I Am Now A Mobile Developer!!</p-->
<%# accountSettings etc has been moved into _user_account_panel.html.erb%>
    <h1><%#= @page_title %></h1>
    <%# Notification div %>
    <% unless flash[:notice].blank? %>
        <div id="notification"><%= flash[:notice] %></div>
    <% else %>
        <div id="notification" style="display: none"></div>
    <% end %>
    <%# Page errors div %>
    <% if flash[:error]
         @page_errors = [] if !@page_errors
         if flash[:error].is_a?(String)
           @page_errors << flash[:error]
         else
           @page_errors += flash[:error]
         end
       end
    %>
    <% if @page_errors && @page_errors.size > 0 %>
        <div id="page_errors" class="error">
          <% if @page_errors.size == 1 %>
              <p>The following problem was found:
                <%= @page_errors[0] %></p>
          <% else %>
              The following problems were found:
              <ul>
                <% @page_errors.each do |e|
                  if e == '</ul>' %>
                        <%= e %>
                    <% elsif e.index('<ul>') %>
                        <li><%= e %>
                    <% else %>
                        <li><%= e %></li>
                    <% end; end %>
              </ul>
          <% end %>
        </div>
    <% else %>
        <div id="page_errors" style="display: none"></div>
    <% end %>

    <%= yield %>
    <% if false # @user  %>
        <hr/>
        <div id="timeout_warning">Your session will time out in
          <%= @session_timeout %> minutes from when this page was loaded. If you
          need more time, you may <%= link_to 'extend your session',
                                              extend_session_path, :target => '_blank' %>.
        </div>
    <% end %>
  </div><%# end of data-role main%>
</div> <%# end of data-role page%>
</body>
</html>

def/proto1/app/views/layouts/nonform.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<%#
# A layout for pages that don't use the FFAR form generation system.
%>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <%= stylesheet_link_tag "manifest_base_package"%>
    <%= stylesheet_link_tag  'non_generated'  %>
    <%= stylesheet_link_tag_for_vendor "/vendor_assets/autocomp/source/auto_completion.css", :media => "screen" %>
    <title><%=  @title %></title>
  </head>
  <body>
   <% if !@show_header.nil? && @show_header %>
      <%= render({:partial=>'form/header_template.rhtml', :handlers=>[:erb]}) %>
    <% end  %>
    <div id="pageContent">
      <h1 style="margin: 0 auto"><%= @title %></h1>
      <% unless flash[:notice].blank? %>
        <div id="notification"><%= flash[:notice] %></div>
      <% end %>
      <% unless flash[:error].blank? %>
        <div id="error"><%= flash[:error] %></div>
      <% end %>
      <div id="formContent">
        <%= yield :layout %>
        <div id="searchResults" style="visibility: hidden" class="form_auto_complete">
          <div id="completionOptionsScroller">
            <span id="completionOptions" class="auto_complete" style="display: block; width: 261px;">
            </span>
          </div>
          <div id="moreResults" style="display: none;">See more items (Ctl Ret)</div>
          <div id="searchCount" style="display: none;">Search Results<!-- place holder for result count,
           needed for height calculation--></div>
          <div id="searchHint">Search Hint<!--place holder--></div>
        </div>
      </div>
    </div>
    <%= javascript_include_tag 'manifest_jquery_show' %>
    <%= javascript_include_tag 'manifest_page_bottom' %>
    <script type="text/javascript">
      //<!-- define a dojo constant we use, to avoid pulling in all of dojo. -->
      dojo = {}; dojo.keys = {}; dojo.keys.F2 = 113;

      Def.FieldDefaults = {};
      Def.Rules.fieldRules_ = {};
      // Set up change event observers to run when code fields are updated.
      Def.fieldObservers_ = {};
      Def.fieldValidations_ = {};

      document.observe("dom:loaded", function() {
        Def.Navigation.setUpNavKeys();
        // sets up user session timeout
        <% if !@user.blank? %>
          Def.Idle.initEvents();
        <% end %>

        <% if Rails.env != 'test' %>
          Def.UsageMonitor.setTimer();
        <% end %>
      });

      <% if !@show_header.nil? && @show_header && !@user.nil? %>
           document.observe("dom:loaded", function() {
             $('fe_user_name').innerHTML = '<%= @user.name %>' ;
      });
      <% end%>
     window._token = '<%= form_authenticity_token -%>';
    </script>
    <%= yield :page_specific_js %>
  </body>
</html>