def/proto1/config/routes.rb
Proto1::Application.routes.draw do

  root :to => "login#login"

  resource :feedback, :only=>[:new, :create]
  resource :contact, :only=>[:new, :create], :controller=>'feedback',
           :type=>'contact_us', :as=>:contact_us
  resources :usage_stats, :only => :create

  resources :phr_home, :only => :index
  get '/phr_home/export_one_profile/:id_shown(/:file_format/:file_name)' =>
                                                   'phr_home#export_one_profile'
  get '/phr_home/get_name_age_gender_updated_labels'
  get '/phr_home/get_removed_listings'
  get '/phr_home/get_one_active_profile_listing'
  get '/phr_home/get_initial_listings'
  get '/phr_home/get_others_listings'
  get '/phr_home/get_access_list'
  put '/phr_home/remove_access'

  post '/share_invitation' => 'share_invitation#create'
  post '/share_invitation/accept_invitation(/:sent_to/:invite_data)' =>
                                      'share_invitation#accept_invitation'
  match '/share_invitation/accept_invitation' =>'share_invitation#accept_invitation',
      :as => 'accept_invitation', :via => [ :get]
  get '/share_invitation/get_pending_share_invitations'
  post '/share_invitation/update_invitations'

  get '/phr_records/archived'=>'phr_records#archived_index', :as=>"archived_phr_records"
  get '/phr_records/message_managers'=>'phr_records#message_managers',
    :as => "message_managers"
  put '/phr_records/:id/archive'=>'phr_records#archive', :as=>"archive_phr_record"
  put '/phr_records/:id/unarchive'=>'phr_records#unarchive', :as=>"unarchive_phr_record"

  resources :phr_records do
    member do
      post 'archive'
      post 'unarchive'
      get 'edit_phr'
      put 'update_phr'
      match 'export', :via => [:get, :post]
    end
    resources :phr_drugs do
      get 'search', :on => :member
    end
    resources :phr_conditions do
      get 'search', :on => :member
      match 'studies', :on=>:collection, :via=>[:get, :post]
    end
    resources :phr_surgical_histories do
      get 'search', :on => :member
    end
    resources :phr_doctor_questions
    resources :phr_medical_contacts
    resources :phr_allergies
    resources :phr_immunizations
    resources :phr_notes

    resources :reminder_options do
      get 'search', :on => :member
    end
    resources :date_reminders do
      get 'hidden', :on => :collection
      member do
        post 'unhide'
        post 'hide'
      end
    end
    resources :phr_panels do
      get 'search', :on => :member
      match 'flowsheet', :via => [:get, :post], :on => :collection
      match 'get_paginated_flowsheet_data_hash', :via => [:get], :on => :collection
      resources :items, :controller=>:phr_panel_items
    end
  end

  get '/phr_records/:id/reminders'=>'phr_records#reminders', :as => "phr_record_reminders"

  get '/captcha/show'=>'captcha#show', :as => "captcha"
  post '/captcha/answer'=>'captcha#answer', :as => "captcha_answer"
  resources :phr_records, :as => "profiles", :controller=> "phr_records"

  match '/accounts/login(.:format)' => 'login#login', :form_name =>'login',
    :as => 'login',  :constraints => { :format => /(default|basic|mobile|)/ },
    :via => [:get, :post]

  match '/accounts/delete_account'=> 'login#delete_account',
    :as=>'delete_account', :via=>[:get, :delete]

  constraints :format=>'' do  # disables URLs like /accounts/new.tmp
    match '/accounts/new' => 'login#add_user', :as => "account_sign_up",
      :via => [:get, :post]
    match '/accounts/email_verification' => 'login#email_verification', :as=>"email_verification",
          :via=> [:get, :post]

    get '/accounts/get_reset_link' => "login#get_reset_link"
    match '/accounts/two_factor' => 'login#handle_two_factor', :form_name=>'login',
      :as => "confirmid", :via =>[:get, :post]
    match '/accounts/reset_account_security' =>'login#reset_account_security',
      :as => 'reset_account_security', :via => [ :get, :post]
    match '/accounts/verify_password' => "login#verify_password",
      :via => [:get, :post, :put]
    match '/accounts/change' => 'login#change_account_settings',
      :as => "account_settings" , :via => :all# includes all http verbs
    match '/accounts/forgot_password' =>'login#forgot_password',
      :as => "reset_password_step_one", :via => [:get, :post]
    match '/accounts/forgot_id' =>'login#forgot_id',
      :as=>"recover_account_id_step_one", :via => [:get, :post]
    post '/accounts/forgot_id_step2' => 'login#forgot_id_step2',
      :as =>"recover_account_id_step_two"
    match '/accounts/change_password' => 'login#change_password',
      :as=>"reset_password_step_two", :via => [:get, :post]
    match '/accounts/update_password' => 'login#update_password',
      :as => 'reset_password_step_three', :via =>[:get, :post]
    match '/accounts/logout' =>'login#logout', :via => :all

    get '/application/extend_session', :as=>'extend_session'
    get '/login/timeout_logoff'

    match '/accounts/demo_login' => 'login#demo_login', :as=>'demo_login',
      :constraints => { :format => /(default|basic|mobile|)/ }, :via => [:get, :post]
  end

  %w(run_tests report_results).each do |action_name|
    get "/acceptance/#{action_name}", controller: 'acceptance', action: action_name, as: "acceptance_#{action_name}"
  end

  match '/forms/:form_name/rules' => "rule#show_rules", :as => "rules",
    :via => [:get, :post]
  match '/forms/:form_name/rules/new' => "rule#new_rule",
    :rendering_form => "edit_general_rule",
    :type => Rule::GENERAL_RULE.to_s,
    :via  => [:get, :post]

  match '/forms/:form_name/rules/:id;edit' => "rule#edit_rule",
    :rendering_form => 'edit_general_rule',
    :via  => [:get, :put]

  match '/forms/:form_name/case_rules/new' => "rule#new_rule",
    :rendering_form => "edit_case_rule",
    :type => Rule::CASE_RULE.to_s,
    :via  => [:get, :post]

  match '/forms/:form_name/case_rules/:id;edit'=> "rule#edit_rule",
    :rendering_form => 'edit_case_rule',
    :via  => [:get, :put]

  match '/rules' =>'rule#index', :via => [:get, :post]

  match '/rule/get_rule_name_list', :via => [:get, :post]

  post '/form/handle_combo_field_change'

  match '/fetch_rules/new' => "rule#new_data_rule",
    :rendering_form =>'edit_phr_fetch_rule',
    :type => Rule::FETCH_RULE.to_s,
    :via  => [:get, :post]

  match '/fetch_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form =>'edit_phr_fetch_rule',
    :via  => [:get, :put]

  match 'form/handle_data_req_for_db_field', :via => [:get, :post]

  match '/reminder_rules/new' => "rule#new_data_rule",
    :rendering_form => "new_reminder_rule",
    :type => Rule::REMINDER_RULE.to_s,
    :via  => [:get, :post]

  match '/reminder_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form => "new_reminder_rule",
    :via  => [:get, :put]

  get '/reminder_rules/show' => "rule#show_reminder_rules",
    :readable_format => 'false'

  get '/reminder_rules/show_in_readable_format' => "rule#show_reminder_rules",
    :readable_format => 'true'

  match '/value_rules/new' => "rule#new_data_rule",
    :rendering_form => "new_value_rule",
    :type => Rule::VALUE_RULE.to_s,
    :via  => [:get, :post]

  match '/value_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form => "new_value_rule",
    :via  => [:get, :put]

  get '/form/get_reviewed_reminders'

  post '/form/update_reviewed_reminders'

  get '/form/get_reminder_count'

  get '/form/get_profiles_updatetimes'

  match '/form/get_prefetched_obx_observations',
    :via  => [:get, :post]

  match '/class_types/' => 'classification#show_class_types',
    :form_name => "classifications", :via => [:get, :post]

  match '/classifications/:parent_id;parent_id' => 'classification#show',
    :form_name => "classifications", :via => [ :get, :post]

  match '/class_types/new' => "classification#new_class_type",
    :form_name => "classification",
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:parent_id;parent_id/new' => "classification#new",
    :form_name => "classification",
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :post]

  match '/class_types/new_item' => 'classification#new_class_type',
    :form_name => "classification",
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:parent_id;parent_id/new_item' => 'classification#new',
    :form_name => 'classification',
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:id;edit' => 'classification#edit',
    :form_name => 'classification',
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :put]

  match '/data_classes/:id;edit' => 'classification#edit',
    :form_name => 'classification',
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :put]

  match '/form/get_search_res_list_by_list_desc', :via => [ :get, :post]

  get '/data'=>'data#index'

  get '/data/export/:id'=>'data#export', :format=>'csv'
  get '/data/export_form_text/:id'=>'data#export_form_text', :format=>'csv'
  post '/data/update'

  match '/help_text'=>'help_text#index', :via => [ :get, :post]
  get '/help_text/list' # list of all help files
  match '/help_text/new', :via => [ :get, :post]
  match '/help_text/edit/:id'=>'help_text#edit', :via => [ :get, :post]

  get '/forms/new' =>'formbuilder#new_form', :form_name=>'FormBuilder'
  post '/forms' => 'formbuilder#save_form'
  get '/forms/:form_name;edit'=>'formbuilder#edit_form'

  get '/admin_home' => 'form#form_index', :form_name=>'admin'

  class RestrictPhrIndexToTests
    def matches?(request)
      Rails.env == 'test'
    end
  end
  get '/profiles' => 'form#form_index', :form_name=>'phr', :as => "profiles_std",
                                     :constraints => RestrictPhrIndexToTests.new

  get '/profiles/:id;edit' => 'form#edit_profile_with_form',
    :form_name=>'phr', :as=>'edit_phr'

def/proto1/app/views/phr_records/_edit_field_group.html.erb
<h1><%=field_group_title %></h1>
<% field_html.each do |fh| %>
<div><%= fh %></div>
<% end %>

def/proto1/app/views/phr_records/_new_edit_fields.html.erb
  <div><%=fd_text_field @fds['pseudonym'], @phr_record.phr %></div>
  <div><%=fd_date_field(@fds['birth_date'], @phr_record.phr) %></div>
  <div><%=fd_prefetched_list(@fds['gender'], @phr_record.phr, @gender_list)%></div>
  <div><%=fd_prefetched_list(@fds['race_or_ethnicity'], @phr_record.phr, @race_list)%></div>

def/proto1/app/views/phr_records/archived_index.html.erb
<%= link_to 'Return to the list of active PHRs', phr_records_path %>

<table border="1">
<% @phr_records.each do |phr_record| %>
  <tr> 
    <th><%= phr_record.phr.pseudonym %></th>
    <td><%= button_to_wo_js 'Restore', unarchive_phr_record_path(phr_record), :method=>:put %></td>
    <td><%= button_to_wo_js 'Destroy', phr_record, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

def/proto1/app/views/phr_records/autosave_warning.html.erb
Unsaved data from a previous session (i.e. autosaved data) was found for the
PHR Record, <%= @phr_record.phr.pseudonym %>.
Autosave is not supported by the Basic HTML Mode, so this would have been
autosaved while you were working with the record in the standard mode.  If you
wish to proceed to work with this record in the basic mode, the autosaved data
will be deleted.  You can either:
<ul>
  <li><%= link_to 'Delete (without review)', request.url + '?drop=true'%>
    the autosave data and continue</li>
  <li><%= link_to 'View', edit_phr_path(@phr_record) %> the record and its autosaved
    changes in Standard Mode.</li>
  <li><%= link_to 'Return', phr_records_path %> to the PHR Management page.
</ul>

def/proto1/app/views/phr_records/edit.html.erb
<%= form_tag phr_record_path, :method=>:put %>
  <%= render 'new_edit_fields' %>

  <%= submit_tag 'Save' %>
  <%= link_to 'Cancel', phr_records_path %>
</form>

def/proto1/app/views/phr_records/edit_phr.html.erb
<%= form_tag update_phr_phr_record_path, :method=>:put %>
  <div><%=fd_prefetched_list(@fds['pregnant'], @phr_record.phr, @pregnant_list)%></div>
  <div><%=fd_date_field(@fds['due_date'], @phr_record.phr) %></div>
  <%= submit_tag 'Save' %>
  <%= link_to 'Cancel', phr_record_path %>
</form>

def/proto1/app/views/phr_records/export.html.erb
<%= form_tag export_phr_record_path, :method=>:post %>
  <p><b>Click the Export button to download the health information to your
      computer.</b>
  <ul><li>
      A file will be created with <%= @phr_record.phr.pseudonym%>'s name in the title, and it
      will be downloaded by your internet browser to your computer.</li>
    <li>The file will include data from <%= @phr_record.phr.pseudonym%>'s health summary and test
      results and trackers information.</li>
    <li>The file will not include any documents you may have uploaded
      (imported).</li>
    <li>You can use most spreadsheet programs to view the information and to
      print a copy for your records or for your health care provider.</li></ul></p>

      <p><b>Warning - to ensure your privacy, avoid downloading personal
          information if you are using a public computer.</b></p>

  <p>Note:  After clicking the Export button, you might have to wait a bit
  (possibly up to a minute depending on the amount of data).  Please be patient
  and do not click the Export button again.</p>
  <%= submit_tag 'Export' %>
  <%= link_to 'Cancel', phr_records_path %>
</form>

def/proto1/app/views/phr_records/index.html.erb
<%= link_to 'Create New PHR', new_phr_record_path %></div>

<% if @phr_records.length > 0 %>
<h2>Saved PHR Records</h2>
<table border="1">
<% @phr_records.each do |phr_record| %>
  <tr> 
    <th><%= phr_record.phr.pseudonym %></th>
    <td><%= link_to 'View/Edit', phr_record, :id=>phr_record.id_shown %></td>
    <td><%= link_to 'Change PHR Record Basics', edit_phr_record_path(phr_record) %></td>
    <td><%= link_to 'Export', export_phr_record_path(phr_record)%></td>
    <td><%= button_to_wo_js 'Archive', archive_phr_record_url(phr_record), :method=>:put %></td>
  </tr>
<% end %>
</table>
<% end # if there are saved PHR records %>

<% if @user.has_archived_phr_records %>
<div id ="archived">
  <%= link_to 'View Archived PHR Records', archived_phr_records_path %>
</div>
<% end %>

<div id="mode_notice">Current page mode:  Basic HTML.
<%=link_to 'Standard mode', '/phr_home'%></div>

def/proto1/app/views/phr_records/new.html.erb
<%= form_tag phr_records_path, :method=>:post %>
  <%= render 'new_edit_fields' %>

  <%= submit_tag 'Save' %>
  <%= link_to 'Cancel', phr_records_path %>
</form>

def/proto1/app/views/phr_records/reminders.html.erb
<p><%= link_to "Back to PHR", phr_record_path(@phr_record) %></p>

<div><%= @reminders.html_safe -%></div>

def/proto1/app/views/phr_records/show.html.erb
<%= link_to 'Back to PHR Management', phr_records_path %>
<ul>
  <li><%= link_to 'Health Reminders', phr_record_reminders_path(@phr_record)  %></li>
  <li><%= link_to 'Date Reminders', phr_record_date_reminders_path(@phr_record)  %></li>
  <li><%= link_to 'Medical Conditions', phr_record_phr_conditions_path(@phr_record) %></li>
  <li><%= link_to 'Drug Records', phr_record_phr_drugs_path(@phr_record) %></li>
  <li><%= link_to 'Allergies and Other Dangerous Reactions', phr_record_phr_allergies_path(@phr_record) %></li>
  <li><%= link_to 'Major Surgeries & Implants', phr_record_phr_surgical_histories_path(@phr_record) %></li>
  <li><%= link_to 'Vaccinations', phr_record_phr_immunizations_path(@phr_record) %></li>
  <li><%= link_to 'Medical Contacts', phr_record_phr_medical_contacts_path(@phr_record) %></li>
  <li><%= link_to 'Questions to Ask Your Doctor', phr_record_phr_doctor_questions_path(@phr_record) %></li>
  <li><%= link_to 'Notes', phr_record_phr_notes_path(@phr_record) %></li>
  <% if @phr_record.phr.gender_C == 'F' %>
  <li><%= link_to 'Pregnancy Status', edit_phr_phr_record_path(@phr_record) %></li>
  <% end %>
  <li><%= link_to PhrPanelsController::PANELS_SECTION_TITLE, phr_record_phr_panels_path(@phr_record) %></li>
</ul>