def/proto1/config/routes.rb
Proto1::Application.routes.draw do

  root :to => "login#login"

  resource :feedback, :only=>[:new, :create]
  resource :contact, :only=>[:new, :create], :controller=>'feedback',
           :type=>'contact_us', :as=>:contact_us
  resources :usage_stats, :only => :create

  resources :phr_home, :only => :index
  get '/phr_home/export_one_profile/:id_shown(/:file_format/:file_name)' =>
                                                   'phr_home#export_one_profile'
  get '/phr_home/get_name_age_gender_updated_labels'
  get '/phr_home/get_removed_listings'
  get '/phr_home/get_one_active_profile_listing'
  get '/phr_home/get_initial_listings'
  get '/phr_home/get_others_listings'
  get '/phr_home/get_access_list'
  put '/phr_home/remove_access'

  post '/share_invitation' => 'share_invitation#create'
  post '/share_invitation/accept_invitation(/:sent_to/:invite_data)' =>
                                      'share_invitation#accept_invitation'
  match '/share_invitation/accept_invitation' =>'share_invitation#accept_invitation',
      :as => 'accept_invitation', :via => [ :get]
  get '/share_invitation/get_pending_share_invitations'
  post '/share_invitation/update_invitations'

  get '/phr_records/archived'=>'phr_records#archived_index', :as=>"archived_phr_records"
  get '/phr_records/message_managers'=>'phr_records#message_managers',
    :as => "message_managers"
  put '/phr_records/:id/archive'=>'phr_records#archive', :as=>"archive_phr_record"
  put '/phr_records/:id/unarchive'=>'phr_records#unarchive', :as=>"unarchive_phr_record"

  resources :phr_records do
    member do
      post 'archive'
      post 'unarchive'
      get 'edit_phr'
      put 'update_phr'
      match 'export', :via => [:get, :post]
    end
    resources :phr_drugs do
      get 'search', :on => :member
    end
    resources :phr_conditions do
      get 'search', :on => :member
      match 'studies', :on=>:collection, :via=>[:get, :post]
    end
    resources :phr_surgical_histories do
      get 'search', :on => :member
    end
    resources :phr_doctor_questions
    resources :phr_medical_contacts
    resources :phr_allergies
    resources :phr_immunizations
    resources :phr_notes

    resources :reminder_options do
      get 'search', :on => :member
    end
    resources :date_reminders do
      get 'hidden', :on => :collection
      member do
        post 'unhide'
        post 'hide'
      end
    end
    resources :phr_panels do
      get 'search', :on => :member
      match 'flowsheet', :via => [:get, :post], :on => :collection
      match 'get_paginated_flowsheet_data_hash', :via => [:get], :on => :collection
      resources :items, :controller=>:phr_panel_items
    end
  end

  get '/phr_records/:id/reminders'=>'phr_records#reminders', :as => "phr_record_reminders"

  get '/captcha/show'=>'captcha#show', :as => "captcha"
  post '/captcha/answer'=>'captcha#answer', :as => "captcha_answer"
  resources :phr_records, :as => "profiles", :controller=> "phr_records"

  match '/accounts/login(.:format)' => 'login#login', :form_name =>'login',
    :as => 'login',  :constraints => { :format => /(default|basic|mobile|)/ },
    :via => [:get, :post]

  match '/accounts/delete_account'=> 'login#delete_account',
    :as=>'delete_account', :via=>[:get, :delete]

  constraints :format=>'' do  # disables URLs like /accounts/new.tmp
    match '/accounts/new' => 'login#add_user', :as => "account_sign_up",
      :via => [:get, :post]
    match '/accounts/email_verification' => 'login#email_verification', :as=>"email_verification",
          :via=> [:get, :post]

    get '/accounts/get_reset_link' => "login#get_reset_link"
    match '/accounts/two_factor' => 'login#handle_two_factor', :form_name=>'login',
      :as => "confirmid", :via =>[:get, :post]
    match '/accounts/reset_account_security' =>'login#reset_account_security',
      :as => 'reset_account_security', :via => [ :get, :post]
    match '/accounts/verify_password' => "login#verify_password",
      :via => [:get, :post, :put]
    match '/accounts/change' => 'login#change_account_settings',
      :as => "account_settings" , :via => :all# includes all http verbs
    match '/accounts/forgot_password' =>'login#forgot_password',
      :as => "reset_password_step_one", :via => [:get, :post]
    match '/accounts/forgot_id' =>'login#forgot_id',
      :as=>"recover_account_id_step_one", :via => [:get, :post]
    post '/accounts/forgot_id_step2' => 'login#forgot_id_step2',
      :as =>"recover_account_id_step_two"
    match '/accounts/change_password' => 'login#change_password',
      :as=>"reset_password_step_two", :via => [:get, :post]
    match '/accounts/update_password' => 'login#update_password',
      :as => 'reset_password_step_three', :via =>[:get, :post]
    match '/accounts/logout' =>'login#logout', :via => :all

    get '/application/extend_session', :as=>'extend_session'
    get '/login/timeout_logoff'

    match '/accounts/demo_login' => 'login#demo_login', :as=>'demo_login',
      :constraints => { :format => /(default|basic|mobile|)/ }, :via => [:get, :post]
  end

  %w(run_tests report_results).each do |action_name|
    get "/acceptance/#{action_name}", controller: 'acceptance', action: action_name, as: "acceptance_#{action_name}"
  end

  match '/forms/:form_name/rules' => "rule#show_rules", :as => "rules",
    :via => [:get, :post]
  match '/forms/:form_name/rules/new' => "rule#new_rule",
    :rendering_form => "edit_general_rule",
    :type => Rule::GENERAL_RULE.to_s,
    :via  => [:get, :post]

  match '/forms/:form_name/rules/:id;edit' => "rule#edit_rule",
    :rendering_form => 'edit_general_rule',
    :via  => [:get, :put]

  match '/forms/:form_name/case_rules/new' => "rule#new_rule",
    :rendering_form => "edit_case_rule",
    :type => Rule::CASE_RULE.to_s,
    :via  => [:get, :post]

  match '/forms/:form_name/case_rules/:id;edit'=> "rule#edit_rule",
    :rendering_form => 'edit_case_rule',
    :via  => [:get, :put]

  match '/rules' =>'rule#index', :via => [:get, :post]

  match '/rule/get_rule_name_list', :via => [:get, :post]

  post '/form/handle_combo_field_change'

  match '/fetch_rules/new' => "rule#new_data_rule",
    :rendering_form =>'edit_phr_fetch_rule',
    :type => Rule::FETCH_RULE.to_s,
    :via  => [:get, :post]

  match '/fetch_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form =>'edit_phr_fetch_rule',
    :via  => [:get, :put]

  match 'form/handle_data_req_for_db_field', :via => [:get, :post]

  match '/reminder_rules/new' => "rule#new_data_rule",
    :rendering_form => "new_reminder_rule",
    :type => Rule::REMINDER_RULE.to_s,
    :via  => [:get, :post]

  match '/reminder_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form => "new_reminder_rule",
    :via  => [:get, :put]

  get '/reminder_rules/show' => "rule#show_reminder_rules",
    :readable_format => 'false'

  get '/reminder_rules/show_in_readable_format' => "rule#show_reminder_rules",
    :readable_format => 'true'

  match '/value_rules/new' => "rule#new_data_rule",
    :rendering_form => "new_value_rule",
    :type => Rule::VALUE_RULE.to_s,
    :via  => [:get, :post]

  match '/value_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form => "new_value_rule",
    :via  => [:get, :put]

  get '/form/get_reviewed_reminders'

  post '/form/update_reviewed_reminders'

  get '/form/get_reminder_count'

  get '/form/get_profiles_updatetimes'

  match '/form/get_prefetched_obx_observations',
    :via  => [:get, :post]

  match '/class_types/' => 'classification#show_class_types',
    :form_name => "classifications", :via => [:get, :post]

  match '/classifications/:parent_id;parent_id' => 'classification#show',
    :form_name => "classifications", :via => [ :get, :post]

  match '/class_types/new' => "classification#new_class_type",
    :form_name => "classification",
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:parent_id;parent_id/new' => "classification#new",
    :form_name => "classification",
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :post]

  match '/class_types/new_item' => 'classification#new_class_type',
    :form_name => "classification",
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:parent_id;parent_id/new_item' => 'classification#new',
    :form_name => 'classification',
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:id;edit' => 'classification#edit',
    :form_name => 'classification',
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :put]

  match '/data_classes/:id;edit' => 'classification#edit',
    :form_name => 'classification',
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :put]

  match '/form/get_search_res_list_by_list_desc', :via => [ :get, :post]

  get '/data'=>'data#index'

  get '/data/export/:id'=>'data#export', :format=>'csv'
  get '/data/export_form_text/:id'=>'data#export_form_text', :format=>'csv'
  post '/data/update'

  match '/help_text'=>'help_text#index', :via => [ :get, :post]
  get '/help_text/list' # list of all help files
  match '/help_text/new', :via => [ :get, :post]
  match '/help_text/edit/:id'=>'help_text#edit', :via => [ :get, :post]

  get '/forms/new' =>'formbuilder#new_form', :form_name=>'FormBuilder'
  post '/forms' => 'formbuilder#save_form'
  get '/forms/:form_name;edit'=>'formbuilder#edit_form'

  get '/admin_home' => 'form#form_index', :form_name=>'admin'

  class RestrictPhrIndexToTests
    def matches?(request)
      Rails.env == 'test'
    end
  end
  get '/profiles' => 'form#form_index', :form_name=>'phr', :as => "profiles_std",
                                     :constraints => RestrictPhrIndexToTests.new

  get '/profiles/:id;edit' => 'form#edit_profile_with_form',
    :form_name=>'phr', :as=>'edit_phr'

def/proto1/app/views/basic/_dup_warning_section.html.erb
<h2>WARNING</h2>
<% if File.exists?(File.join(Rails.root, 'app', 'views', @table, '_dup_warnings.html.erb')) %>
  <%= render "#{@table}/dup_warnings" %>
<% else %>
  <%# The standard message.  This is from controlled_edit_table.js
      warnAboutDuplicates.  If you change this message, also update it there. %>
  You have more than one record for <%= h @dup_warning_data %>.
  That is allowed, but these tables are really intended to be 
  profiles rather than histories.
<% end %>
<p>
<%= check_box_tag 'dup_ok' %><%= label_tag 'dup_ok', 'Acknowledge warnings' %>
</p>

def/proto1/app/views/basic/_radio_button.html.erb
<label for="<%=button_id%>">
<input type="radio" value="<%=value%>" id="<%=button_id%>"
  name="<%=form_obj%>[<%=button_group%>]"<%=' checked' if checked %>>
  <%= label %>
</label>

def/proto1/app/views/basic/table_edit.html.erb
<%= form_tag send('phr_record_'+@table.singularize+'_path',
    :phr_record_id=>@phr_record), :method=>:put %>
  <%= render 'basic/dup_warning_section' if @dup_warning_data %>
  <%= render 'new_edit_fields' %>
</form>

def/proto1/app/views/basic/table_index.html.erb
<% s_table_name = @table.singularize %>

<%= link_to 'New', send('new_phr_record_'+s_table_name+'_path', @phr_record) %>
&nbsp;
<%= link_to 'Back to PHR', phr_record_path(@phr_record)%>
&nbsp;
<%= render('extra_table_nav_links') if lookup_context.template_exists?(
  'extra_table_nav_links', @table, true)%>
<%= help_button get_help_url(@section_fd) %>

<% if @records.length > 0 %>
<% has_info_link = @records[0].respond_to?('info_link') %>
<table border="1">
  <tr>
    <% @db_fields.each_with_index do |col, i| %>
      <th><%=@labels[col]%></th>
      <% if i == @main_field_index %>
        <th>Delete?</th>
      <% end %>
    <% end %>
    <% if has_info_link %>
      <th>Info Page</th>
    <% end %>
  </tr>
  <% edit_path_method = 'edit_phr_record_'+s_table_name+'_path';
     delete_path_method = 'phr_record_'+s_table_name+'_path'%>
  <% @records.each do |d| %>
    <tr>
      <% @db_fields.each_with_index do |col, i| %>
        <% if i == @main_field_index %>
          <th><a href="<%= send(edit_path_method, @phr_record, d)%>"
              ><%=d.send(col)%></a></th>
          <td><%= button_to_wo_js 'Delete', send(delete_path_method, @phr_record, d),
           :confirm => 'Are you sure?', :method => :delete %></td>
        <% else %>
          <td><%=d.send(col)%></td>
        <% end %>
      <% end %>
      <% if has_info_link %>
        <td>
        <% link_data = d.info_link %>
        <% if link_data %>
          <% if link_data.class == String %>
            <%= link_to 'Info', d.info_link, :target=>'_blank' %>
          <% else # assume a hash %>
            <% link_data.each do |url_data| %>
              <%= link_to url_data[1], url_data[0], :target=>'_blank' %>
            <% end %>
          <% end %>
        <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<% end %>

def/proto1/app/views/basic/table_new.html.erb
<%= form_tag send('phr_record_'+@table+'_path', :phr_record_id=>@phr_record) %>
  <%= render 'basic/dup_warning_section' if @dup_warning_data %>
  <%= render "#{@table}/new_edit_fields" %>
</form>

def/proto1/app/views/basic/table_search.html.erb
<% s_table_name = @table.singularize %>
<%= form_tag send('search_phr_record_'+s_table_name+'_path', :phr_record_id=>@phr_record, :id=>'new'), :method=>'get' %>
<% @search_text = h(@search_text) %>
<%=basic_text_field 'Enter part of the name to look up', 'phr', 'search_text', nil, :value=>@search_text%>
<%=submit_tag 'Search' %>
<% if @displayed_data  %>
<hr>
  <% if @total_hits > 0 or @item_codes.length > 0 %>
    <% if @total_hits > 0 %>
      Select a matching name from below, or search again:
    <% else %>
      There were no matches, but the following items were found that were close:
    <% end %>
    <ul>
    <% @displayed_data.each_with_index do |e, i| %>
     <li><%= link_to e, send('new_phr_record_'+s_table_name+'_path')+'?code='+@item_codes[i] %></li>
    <% end %>
    </ul>
    You may also use your original search string as the item name:
  <% else %>
    No results were found.  Either try searching again, or use your original
    search string as the item name:
  <% end %>
  <%= link_to @search_text, send('new_phr_record_'+s_table_name+'_path')+'?name='+@search_text %>
<% end %>
</form>
<%= link_to 'Cancel', send('phr_record_'+@table+'_path') %>

def/proto1/app/views/basic/table_select.html.erb
<%# This handles the first part of creating a record for a table where the
  main item nees to be selected by first picking a type, and then picking a
  name from a sub-list.  %>
Select <%=@item_name%>:
<ul>
<% s_table_name = @table.singularize %>
<% if @type_code || @no_type %>
  <li><%= form_tag send('new_phr_record_'+s_table_name+'_path'), :method=>'get' %>
     <%= hidden_field_tag :type_C, @type_code %>
     <%=basic_text_field 'Other name (not in the list below)',
     BasicModeController::FD_FORM_OBJ_NAME, 'other_name'%>
     <%= submit_tag 'Create' %>
    </form></li>
<% end %>

<%# Support one level of headings.  Heading items have codes that start
  # with "heading" %>
<% in_list = nil; @items.each do |item_info| %>
  <% code = item_info[0]; if code=~ /\Aheading/ %>
    <% if in_list %>
      </ul></li>
    <% end; in_list = 1 %>
      <li><b><%= item_info[1] %>:</b><ul>
  <% else ;  @link_params[@code_param] = code %>
    <li><%= link_to item_info[1],  send('new_phr_record_'+s_table_name+'_path',
                                        @link_params) %></li>
  <% end %>
<% end %>
<% if in_list %>
  </ul>
<% end %>
</ul>
<%= link_to 'Cancel', send('phr_record_'+@table+'_path') %>