def/proto1/config/routes.rb
Proto1::Application.routes.draw do

  root :to => "login#login"

  resource :feedback, :only=>[:new, :create]
  resource :contact, :only=>[:new, :create], :controller=>'feedback',
           :type=>'contact_us', :as=>:contact_us
  resources :usage_stats, :only => :create

  resources :phr_home, :only => :index
  get '/phr_home/export_one_profile/:id_shown(/:file_format/:file_name)' =>
                                                   'phr_home#export_one_profile'
  get '/phr_home/get_name_age_gender_updated_labels'
  get '/phr_home/get_removed_listings'
  get '/phr_home/get_one_active_profile_listing'
  get '/phr_home/get_initial_listings'
  get '/phr_home/get_others_listings'
  get '/phr_home/get_access_list'
  put '/phr_home/remove_access'

  post '/share_invitation' => 'share_invitation#create'
  post '/share_invitation/accept_invitation(/:sent_to/:invite_data)' =>
                                      'share_invitation#accept_invitation'
  match '/share_invitation/accept_invitation' =>'share_invitation#accept_invitation',
      :as => 'accept_invitation', :via => [ :get]
  get '/share_invitation/get_pending_share_invitations'
  post '/share_invitation/update_invitations'

  get '/phr_records/archived'=>'phr_records#archived_index', :as=>"archived_phr_records"
  get '/phr_records/message_managers'=>'phr_records#message_managers',
    :as => "message_managers"
  put '/phr_records/:id/archive'=>'phr_records#archive', :as=>"archive_phr_record"
  put '/phr_records/:id/unarchive'=>'phr_records#unarchive', :as=>"unarchive_phr_record"

  resources :phr_records do
    member do
      post 'archive'
      post 'unarchive'
      get 'edit_phr'
      put 'update_phr'
      match 'export', :via => [:get, :post]
    end
    resources :phr_drugs do
      get 'search', :on => :member
    end
    resources :phr_conditions do
      get 'search', :on => :member
      match 'studies', :on=>:collection, :via=>[:get, :post]
    end
    resources :phr_surgical_histories do
      get 'search', :on => :member
    end
    resources :phr_doctor_questions
    resources :phr_medical_contacts
    resources :phr_allergies
    resources :phr_immunizations
    resources :phr_notes

    resources :reminder_options do
      get 'search', :on => :member
    end
    resources :date_reminders do
      get 'hidden', :on => :collection
      member do
        post 'unhide'
        post 'hide'
      end
    end
    resources :phr_panels do
      get 'search', :on => :member
      match 'flowsheet', :via => [:get, :post], :on => :collection
      match 'get_paginated_flowsheet_data_hash', :via => [:get], :on => :collection
      resources :items, :controller=>:phr_panel_items
    end
  end

  get '/phr_records/:id/reminders'=>'phr_records#reminders', :as => "phr_record_reminders"

  get '/captcha/show'=>'captcha#show', :as => "captcha"
  post '/captcha/answer'=>'captcha#answer', :as => "captcha_answer"
  resources :phr_records, :as => "profiles", :controller=> "phr_records"

  match '/accounts/login(.:format)' => 'login#login', :form_name =>'login',
    :as => 'login',  :constraints => { :format => /(default|basic|mobile|)/ },
    :via => [:get, :post]

  match '/accounts/delete_account'=> 'login#delete_account',
    :as=>'delete_account', :via=>[:get, :delete]

  constraints :format=>'' do  # disables URLs like /accounts/new.tmp
    match '/accounts/new' => 'login#add_user', :as => "account_sign_up",
      :via => [:get, :post]
    match '/accounts/email_verification' => 'login#email_verification', :as=>"email_verification",
          :via=> [:get, :post]

    get '/accounts/get_reset_link' => "login#get_reset_link"
    match '/accounts/two_factor' => 'login#handle_two_factor', :form_name=>'login',
      :as => "confirmid", :via =>[:get, :post]
    match '/accounts/reset_account_security' =>'login#reset_account_security',
      :as => 'reset_account_security', :via => [ :get, :post]
    match '/accounts/verify_password' => "login#verify_password",
      :via => [:get, :post, :put]
    match '/accounts/change' => 'login#change_account_settings',
      :as => "account_settings" , :via => :all# includes all http verbs
    match '/accounts/forgot_password' =>'login#forgot_password',
      :as => "reset_password_step_one", :via => [:get, :post]
    match '/accounts/forgot_id' =>'login#forgot_id',
      :as=>"recover_account_id_step_one", :via => [:get, :post]
    post '/accounts/forgot_id_step2' => 'login#forgot_id_step2',
      :as =>"recover_account_id_step_two"
    match '/accounts/change_password' => 'login#change_password',
      :as=>"reset_password_step_two", :via => [:get, :post]
    match '/accounts/update_password' => 'login#update_password',
      :as => 'reset_password_step_three', :via =>[:get, :post]
    match '/accounts/logout' =>'login#logout', :via => :all

    get '/application/extend_session', :as=>'extend_session'
    get '/login/timeout_logoff'

    match '/accounts/demo_login' => 'login#demo_login', :as=>'demo_login',
      :constraints => { :format => /(default|basic|mobile|)/ }, :via => [:get, :post]
  end

  %w(run_tests report_results).each do |action_name|
    get "/acceptance/#{action_name}", controller: 'acceptance', action: action_name, as: "acceptance_#{action_name}"
  end

  match '/forms/:form_name/rules' => "rule#show_rules", :as => "rules",
    :via => [:get, :post]
  match '/forms/:form_name/rules/new' => "rule#new_rule",
    :rendering_form => "edit_general_rule",
    :type => Rule::GENERAL_RULE.to_s,
    :via  => [:get, :post]

  match '/forms/:form_name/rules/:id;edit' => "rule#edit_rule",
    :rendering_form => 'edit_general_rule',
    :via  => [:get, :put]

  match '/forms/:form_name/case_rules/new' => "rule#new_rule",
    :rendering_form => "edit_case_rule",
    :type => Rule::CASE_RULE.to_s,
    :via  => [:get, :post]

  match '/forms/:form_name/case_rules/:id;edit'=> "rule#edit_rule",
    :rendering_form => 'edit_case_rule',
    :via  => [:get, :put]

  match '/rules' =>'rule#index', :via => [:get, :post]

  match '/rule/get_rule_name_list', :via => [:get, :post]

  post '/form/handle_combo_field_change'

  match '/fetch_rules/new' => "rule#new_data_rule",
    :rendering_form =>'edit_phr_fetch_rule',
    :type => Rule::FETCH_RULE.to_s,
    :via  => [:get, :post]

  match '/fetch_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form =>'edit_phr_fetch_rule',
    :via  => [:get, :put]

  match 'form/handle_data_req_for_db_field', :via => [:get, :post]

  match '/reminder_rules/new' => "rule#new_data_rule",
    :rendering_form => "new_reminder_rule",
    :type => Rule::REMINDER_RULE.to_s,
    :via  => [:get, :post]

  match '/reminder_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form => "new_reminder_rule",
    :via  => [:get, :put]

  get '/reminder_rules/show' => "rule#show_reminder_rules",
    :readable_format => 'false'

  get '/reminder_rules/show_in_readable_format' => "rule#show_reminder_rules",
    :readable_format => 'true'

  match '/value_rules/new' => "rule#new_data_rule",
    :rendering_form => "new_value_rule",
    :type => Rule::VALUE_RULE.to_s,
    :via  => [:get, :post]

  match '/value_rules/:id;edit' => "rule#edit_data_rule",
    :rendering_form => "new_value_rule",
    :via  => [:get, :put]

  get '/form/get_reviewed_reminders'

  post '/form/update_reviewed_reminders'

  get '/form/get_reminder_count'

  get '/form/get_profiles_updatetimes'

  match '/form/get_prefetched_obx_observations',
    :via  => [:get, :post]

  match '/class_types/' => 'classification#show_class_types',
    :form_name => "classifications", :via => [:get, :post]

  match '/classifications/:parent_id;parent_id' => 'classification#show',
    :form_name => "classifications", :via => [ :get, :post]

  match '/class_types/new' => "classification#new_class_type",
    :form_name => "classification",
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:parent_id;parent_id/new' => "classification#new",
    :form_name => "classification",
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :post]

  match '/class_types/new_item' => 'classification#new_class_type',
    :form_name => "classification",
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:parent_id;parent_id/new_item' => 'classification#new',
    :form_name => 'classification',
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :post]

  match '/classifications/:id;edit' => 'classification#edit',
    :form_name => 'classification',
    :node_type => Classification::CLASS_NODE_TYPE, :via => [ :get, :put]

  match '/data_classes/:id;edit' => 'classification#edit',
    :form_name => 'classification',
    :node_type => Classification::CLASS_ITEM_NODE_TYPE, :via => [ :get, :put]

  match '/form/get_search_res_list_by_list_desc', :via => [ :get, :post]

  get '/data'=>'data#index'

  get '/data/export/:id'=>'data#export', :format=>'csv'
  get '/data/export_form_text/:id'=>'data#export_form_text', :format=>'csv'
  post '/data/update'

  match '/help_text'=>'help_text#index', :via => [ :get, :post]
  get '/help_text/list' # list of all help files
  match '/help_text/new', :via => [ :get, :post]
  match '/help_text/edit/:id'=>'help_text#edit', :via => [ :get, :post]

  get '/forms/new' =>'formbuilder#new_form', :form_name=>'FormBuilder'
  post '/forms' => 'formbuilder#save_form'
  get '/forms/:form_name;edit'=>'formbuilder#edit_form'

  get '/admin_home' => 'form#form_index', :form_name=>'admin'

  class RestrictPhrIndexToTests
    def matches?(request)
      Rails.env == 'test'
    end
  end
  get '/profiles' => 'form#form_index', :form_name=>'phr', :as => "profiles_std",
                                     :constraints => RestrictPhrIndexToTests.new

  get '/profiles/:id;edit' => 'form#edit_profile_with_form',
    :form_name=>'phr', :as=>'edit_phr'

def/proto1/app/views/form/_deferred_fetch.rhtml.erb
<script type="text/javascript">//<![CDATA[
  var <%=fld_id%>_deferred_fetch =
    new Def.Autocompleter.Prefetch('<%= fld_id %>', <%= matchListValue %>, []);
  //]]>
</script><noscript>Javascript Required</noscript>

def/proto1/app/views/form/_flash_lso_template_field.rhtml.erb
  <p class="screen_reader_only">Flash object with no visible content</p>
	<object width="1" height="1" id="CBCookie">
	<param name="movie" value="/CB_Cookie.swf" />
  <param name="quality" value="high" />
  <param name="bgcolor" value="#ffcc00" />
  <embed src="/CB_Cookie.swf" quality="high" bgcolor="#ffcc00" width="1" height="1" name="CBCookie"
  align="middle"  type="application/x-shockwave-flash" />
	</object>

def/proto1/app/views/form/_form_list.rhtml.erb
<% if forms.size>0 %>
  <h2><%= title %></h2>
  <ul>
    <% forms.each do |f| %>
      <li><a href="/form/show/<%=f.form_name%>"><%=f.form_title%></a>
          &nbsp;&nbsp;<a href="/forms/<%=f.form_name%>/rules">[rules]</a></li>
    <% end %>
  </ul>
<% end %>

def/proto1/app/views/form/_horizontal_field_group_row.rhtml.erb
    <tr class="repeatingLine<% if @read_only_mode%> saved_row<%end
     if labeled_fields %> labeled_fields<%end%>"
     rowId="<%=row_id%>" 
     suffix="<%=row_suffix%>" style="<% if row_id==0
     %>display: none; <% end %>width: 99%">
      <% row_fields.each_with_index do |rf, i| %>
              
      <td <% if hidden_cols[i] %> style="width: 0; display: none;"<%end%>
         <% if !tagAttrs[i].empty? %>
            <% tagAttrs[i].each do |k, v| %> <%=k%>="<%=v%>" <%end end
          %> ><%= rf %></td>
      <% end %>
    </tr>
    <% embedded_rows.each do |er| %>
    <tr class="embeddedRow<% if @read_only_mode%> saved_row<%end%>"
     rowId="<%=row_id%>"<% if row_id==0 %> style="display: none"<% end %>>
     <td colspan="<%= num_cols %>">
       <%= er %>
     </td>
    </tr>
    <% end %>

def/proto1/app/views/form/_panel_static_table.rhtml.erb
<% if is_user_data %>  
  TestPanel.panelListOption['fdID']=<%=fd_id%>,
  TestPanel.panelListOption['colNum']=<%=col_num%>
  TestPanel.panelListOption['listID']='<%=id%>'
  TestPanel.panelListOption['dataURL']='<%=user_data_url%>'
<% end %>

def/proto1/app/views/form/_panel_test_field.rhtml.erb
<!-- Display Panel group-->
<%= form_for form_obj  do |f| %>
   <% panel_fields.each do |field| %>
      <%= displayField(field, f, false, nil, suffix) %>
   <% end %>
<% end %>

def/proto1/app/views/form/_profiles_list_field.rhtml.erb
<% # Template for new PHR Home page active profile listings section %>

<div id="topSection">
  <button id="add_new" class="rounded" type="button"
          onclick="Def.PHRHome.addNew();">
    <span>Add New Person</span></button>

  <table id="profiles_list">

   <tr id="profile_list_header_row">
   <th> </th>
   <th> </th>
   <th>Person</th>
   <th class="updated_header">Updated</th>
   <th></th>
   <th>Notifications</th>
   <th></th>
   <th></th>
   </tr>

    <% if !@profiles.nil? %>
      <% row = 0 %>
      <% @profiles.each do |profile| %>

        <% row += 1 %>
        <% row_s = row.to_s %>
        <% @profile_ids_shown[profile.id_shown] = row %>

          <%= render({:partial =>'form/profile_listing.rhtml',
                      :handlers =>[:erb],
                      :locals=>{:row_s=>row_s, :profile=>profile}}).html_safe %>

      <% end %> <!-- end profiles.each -->
    <% end %> <!-- end if !@profiles.nil? -->
  </table>

</div> <!-- topSection -->

def/proto1/app/views/form/_radio_group.rhtml.erb
<!-- radio button group -->
<div id="<%=grp_id%>" class="<%=classes%>">
  <% buttons.each do |radio_button| %>
    <label for="<%=radio_button['id'] %>" class="radio_button">
      <input type="radio" class="radio_button" name="<%=grp_name%>" id="<%=radio_button['id']%>"
           value="<%=radio_button['value']%>"></input><%=radio_button['label']%>
    </label>
    <% if orientation == 'vertical' %> <br/> <% end %>
  <% end %>
</div>

def/proto1/app/views/form/_saved_tests_field.rhtml.erb
<table id="saved_panels" style="width: 100%">
  <colgroup>
    <col style="width: 8em; min-width: 8em" />
    <col style="" />
    <col style="width: 0; display: none" />
  </colgroup>
  <thead>
    <tr><td>Last entry date</td><td>Panel name</td><td style="display:none;"></td></tr>
  </thead>
</table>

def/proto1/app/views/form/_search_field_autocomp.rhtml.erb
var opts = {headerBar: 'fe_form_header_0_expcol'};<% if dataUrl %>
opts['dataRequester']= new Def.RecordDataRequester($('<%= id %>'), '<%=dataUrl%>',
  <%=dataReqInput.to_json.html_safe%>, <%= raw dataReqOutput.to_json%>, <%=outputToSameGroup%>)<%end
%><% if !matchListValue.nil? %>
opts['matchListValue']=<%= matchListValue %><%end
%><% if !suggestionMode.nil? %>
opts['suggestionMode']=<%= suggestionMode %><%end
%><% if !button_id.nil? %>
opts['buttonID']='<%= button_id %>'<%end
%><% if !autocomp.nil? %>
opts['autocomp']=<%= autocomp %><%end%>
var <%=id%>_autoComp =
  new Def.Autocompleter.Search('<%= id %>',
    '<%=resultsUrl%>', opts);

def/proto1/app/views/form/_test_panel_timeline.rhtml.erb
<%# A timeline view div %>
<div class="panel_timeline">
<table style="border-collapse: collapse; width:100%;">
  <tr>
    <td class="fixed_col">
  <%# panel def div %>
  <div class="panel_def" p_no=<%=@panel_def[0]['loinc_num']%>>
    <table >
      <%# 3 extra rows %>
      <tr><th class="test_name">&nbsp;</th><th class="sparkline_chart">&nbsp;</th></tr>
      <tr><th>&nbsp;</th><th>&nbsp;</th></tr>
      <tr><th>&nbsp;</th><th>&nbsp;</th></tr>
      <%- @panel_def.each do |panel| -%>
        <%- if !panel.empty? -%>
          <%- if panel['panel_separator'] -%>
          <%-   class_name ="panel_separator" -%>
          <%-   value='&nbsp;' -%>
          <%- else -%>
            <%- value=panel['name'] -%>
            <%- if !panel['is_test'] -%>
            <%-   class_name ="panel_header " -%>
            <%- else -%>
            <%-   class_name =" " -%>
            <%-   units=panel['units'] -%>
            <%-   value += " (" + units + ")" if !units.blank? -%>
            <%- end -%>
            <%- if panel['no_data'] -%>
            <%-   class_name +="no_data " -%>
            <%- end -%>
            <%- if panel['panel_info'] -%>
            <%-   class_name +="panel_info " -%>
            <%- end -%>
            <%- display_level ="panel_l" + panel['disp_level'].to_s -%>
            <%- class_name += display_level -%>
          <%- end -%>
        <%- else -%>
          <%-   class_name =" " -%>
          <%-   value='&nbsp;' -%>
        <%- end -%>
        <%- if units.blank? -%>
        <%-   common_units = '' -%>
        <%- else -%>
        <%-   common_units = 'units="' + units + '"'-%>
        <%- end -%>
        <tr class="<%=  class_name.html_safe%>" <%=common_units.html_safe%>>
          <td class="test_name" title="<%=value.html_safe%>"><%=value.html_safe%></td>
          <%# data and div for sparkline charts %>
          <td class="sparkline_chart" l_no="<%=panel['loinc_num']%>">
            <%- if panel['numOfRecords'] && panel['numOfRecords'] > 0 -%>
              <input class="forplot" type="checkbox" title="Click to select multiple timeline graphs" />
              <div class="sparkline" onclick ="TestPanel.Flot.sparklineClickHandler(this)" title="Click to view one or more timeline graphs">
              </div>              
            <%- end -%>
          </td>
        <%# end of sparkline charts%>
        </tr>
      <%- end -%>
    </table>
  </div>
<%# data %>
</td><td style="vertical-align:top;">
  <%# test data %>
  <div class="test_data_table_wrapper">
    <div class="test_data_table">
      <table p_no=<%=@panel_def[0]['loinc_num'].html_safe %> >
        <%# define columns %>
        <%- @panel_date.each do |date| -%>
          <%- obr_id = date.keys[0] -%>
          <%- p_ln = date.values[0][5] -%>
          <%- p_name = date.values[0][6] -%>
          <%- col_class=date.values[0][4].join(' ')-%>
          <%- if obr_id.include?('sum') -%>
            <col class="<%= col_class.html_safe%>"> </col>
          <%- else -%>
            <col class='<%= col_class.html_safe%>' obr_id='<%=obr_id%>' p_ln='<%=p_ln.html_safe%>' p_name="<%=p_name%>" > </col>
          <%- end -%>
        <%- end -%>
        <%# add data table column headers %>
        <%# year %>
        <tr class="datetime_header">
          <%- @panel_date.each do |date| -%>
            <%- value=date.values[0][0] -%>
            <%- col_class=date.values[0][4].join(' ') -%>
            <th class="<%= col_class.html_safe %>" >
                <%= (value.blank? ? '&nbsp;': value).html_safe %>
            </th>
          <%- end -%>
        </tr>
        <%# month-day, or the group %>
        <tr class="datetime_header">
          <%- @panel_date.each do |date| 
             value=date.values[0][1] 
             col_class=date.values[0][4].join(' ') -%>
            <th class="<%= col_class.html_safe%>">
                <%= (value.blank? ? '&nbsp;': value).html_safe %>
            </th>
          <%- end -%>
        </tr>
        <%# time or the expand button %>
        <tr class="datetime_header">
          <% @panel_date.each do |date| 
             value=date.values[0][2] 
             value ='&nbsp;' if value.blank? 
             col_class=date.values[0][4].join(' ') 
	     img_html = date.values[0][4].include?('sum') ? 
               image_tag("blank.gif", :class=>"sprite_icons-expand exp_column",
               :onclick=>"TestPanel.expColColumn(this)", :alt=>'Expand', :title=>'Expand')
               : '' -%> 
            <th class="<%= col_class.html_safe%>" >
                <%= (value + img_html).html_safe%>
            </th>
          <%- end -%>
        </tr> 
        <%# add the data table %>
        <%- index=0 -%>
        <%- @panel_data.each do |obx_rec| -%>
          <tr>
          <%- @panel_date.each do |date | -%>
            <%- obr_id = date.keys[0] -%>
            <%# check column class %>
            <%- col_class=date.values[0][4].clone -%>
            <%- if obx_rec.empty? || !@panel_def[index]['is_test'] -%>
              <%- if @panel_def[index]['no_data'] -%>
                <%- cell_value =  '-' -%>
                <%- col_class << 'no_data' -%>
              <%- elsif @panel_def[index]['panel_separator']-%>
                <%- cell_value =  '' -%>
                <%- col_class << 'panel_separator' -%>            
              <%- else -%>
                <%- cell_value = '' -%>
                <%- display_level ="panel_l" + @panel_def[index]['disp_level'].to_s -%>
                <%- col_class << 'panel_header' -%>
                <%- col_class << display_level -%>
               <%- end -%>
            <%- else -%>
              <%- if !obx_rec[obr_id].nil? && !obx_rec[obr_id].empty? -%>
                <%- value = obx_rec[obr_id][0].blank? ? '&nbsp' : obx_rec[obr_id][0] -%>
                <%- has_data = obx_rec[obr_id][9] -%>
                <%- if !has_data -%>
                  <%- cell_value ='-' -%>
                  <%- col_class << 'no_data' -%>
                <%- else -%>
                  <%# display units with value if there's one %>
                  <%- units = obx_rec[obr_id][2] -%>
                  <%- if !units.blank? -%>
                  <%-   value += " " + units -%>
                  <%- end -%>
                  <%# display abnormal flag with value if there's one %>
                  <%- abnormal_flag = obx_rec[obr_id][1] -%>
                  <%- if abnormal_flag.blank? -%>
                    <%- cell_value = value + '<input class="readonly_field flag" readonly="readonly"> </input>' -%>
                  <%- else -%>
                    <%- cell_value = value + '<input class="readonly_field flag" readonly="readonly" value=' + abnormal_flag + '></input>'  -%>
                  <%- end -%>
                <%- end -%>
              <%- else -%>
                <%- cell_value ='-' -%>
                <%- col_class << 'no_data' -%>
              <%- end -%>
            <%- end -%>
            <td class="<%= col_class.join(' ').html_safe %>" >
              <%= cell_value.html_safe %>
            </td>
          <%- end -%>
          </tr>
          <%- index +=1 -%>
        <%- end -%>
      </table>
    </div>
  </div>
</td></tr></table>
</div>

def/proto1/app/views/form/index.rhtml.erb
<!DOCTYPE html PUBLIC "-//W#C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml:
    xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title>Data Entry Framework:  Index of Forms</title>
</head>
<body>
  <h1>Index of Forms</h1>
  <%= render(:partial=>'form_list.rhtml', :handlers=>[:erb], :locals=>{:forms=>@public_forms,
             :title=>'Public Forms'}) %>
  <%= render(:partial=>'form_list.rhtml', :handlers=>[:erb], :locals=>{:forms=>@protected_forms,
             :title=>'Password Protected Forms'}) %>
  <% if (@private_forms) %>
    <%= render(:partial=>'form_list.rhtml', :handlers=>[:erb], :locals=>{:forms=>@private_forms,
               :title=>'Internal (Private to TBD - your organization) Forms'}) %>
  <% end %>
</body>
</html>

def/proto1/app/views/form/vsplit.rhtml.erb
<frameset cols="67%, 33%">
  <frame name='main' src="/form/show/<%=params[:id]%>" />
  <frame name='sub' src="/form/vsplitSub" />
</frameset>